# Generated by Django 5.0.4 on 2024-05-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='wallet_id',
            field=models.CharField(default='', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
